# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: gh-pages

on:
  push:
    branches: [1x]
  pull_request:
    branches: [1x]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          yarn install
          npm run build:demo

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          github_token: ${{ secrets.PERSONAL_SECRET_TOKEN2 }}
          publish_dir: ./dist
