name: test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Build simple-panzoom
        run: pnpm --filter ./packages/simple-panzoom build

      - name: Build sketch-ruler
        run: pnpm --filter ./packages/sketch-ruler build

      - name: Run tests
        run: pnpm test

      - name: Build docs
        run: pnpm build:demo

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'push'
        with:
          publish_dir: ./packages/docs/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
